use super::*;

mod arith;
mod calls;
mod casts;
mod control;
mod mem;

pub(super) struct FnCx<'ctx> {
    pub(super) context: &'ctx Context,
    pub(super) sqrt_fn: Option<FunctionValue<'ctx>>,
    pub(super) fma_fn: Option<FunctionValue<'ctx>>,
    pub(super) tbaa_kind: u32,
    pub(super) tbaa_header: inkwell::values::MetadataValue<'ctx>,
    pub(super) tbaa_payload: inkwell::values::MetadataValue<'ctx>,
    pub(super) builder: Builder<'ctx>,
    pub(super) funcs: BTreeMap<String, FunctionValue<'ctx>>,
    pub(super) alloc: FunctionValue<'ctx>,
    pub(super) release: FunctionValue<'ctx>,
    pub(super) genref_create: FunctionValue<'ctx>,
    pub(super) genref_get: FunctionValue<'ctx>,
    pub(super) genref_invalidate: FunctionValue<'ctx>,
    pub(super) retain: FunctionValue<'ctx>,
    pub(super) concat: FunctionValue<'ctx>,
    pub(super) string_split: FunctionValue<'ctx>,
    pub(super) streq: FunctionValue<'ctx>,
    pub(super) strcmp: FunctionValue<'ctx>,
    pub(super) print_val: FunctionValue<'ctx>,
    pub(super) print_str: FunctionValue<'ctx>,
    pub(super) int_to_str: FunctionValue<'ctx>,
    pub(super) float_to_str: FunctionValue<'ctx>,
    pub(super) bool_to_str: FunctionValue<'ctx>,
    pub(super) any_to_str: FunctionValue<'ctx>,
    pub(super) eq_any_str: FunctionValue<'ctx>,
    pub(super) eq_any: FunctionValue<'ctx>,
    pub(super) release_str: FunctionValue<'ctx>,
    pub(super) array_new: FunctionValue<'ctx>,
    pub(super) array_push: FunctionValue<'ctx>,
    pub(super) array_get: FunctionValue<'ctx>,
    pub(super) array_get_unchecked: FunctionValue<'ctx>,
    pub(super) array_set_unchecked: FunctionValue<'ctx>,
    pub(super) array_set: FunctionValue<'ctx>,
    pub(super) array_len: FunctionValue<'ctx>,
    pub(super) string_len: FunctionValue<'ctx>,
    pub(super) string_slice: FunctionValue<'ctx>,
    pub(super) string_index_of: FunctionValue<'ctx>,
    pub(super) string_index_of_from: FunctionValue<'ctx>,
    pub(super) string_trim: FunctionValue<'ctx>,
    pub(super) string_char_code_at: FunctionValue<'ctx>,
    pub(super) string_from_char_code: FunctionValue<'ctx>,
    pub(super) array_pop_fn: FunctionValue<'ctx>,
    pub(super) any_box: FunctionValue<'ctx>,
    pub(super) any_unbox: FunctionValue<'ctx>,
    pub(super) any_unbox_heap: FunctionValue<'ctx>,
    pub(super) any_retain: FunctionValue<'ctx>,
    pub(super) any_release_box: FunctionValue<'ctx>,
    pub(super) any_release: FunctionValue<'ctx>,
    pub(super) heap_track: FunctionValue<'ctx>,
    pub(super) closure_new: FunctionValue<'ctx>,
    pub(super) closure_set: FunctionValue<'ctx>,
    pub(super) closure_release: FunctionValue<'ctx>,
    pub(super) spawn_closure: FunctionValue<'ctx>,
    pub(super) join_val: FunctionValue<'ctx>,
    pub(super) join_err: FunctionValue<'ctx>,
    pub(super) task_val: FunctionValue<'ctx>,
    pub(super) task_err: FunctionValue<'ctx>,
    pub(super) pool_new: FunctionValue<'ctx>,
    pub(super) submit_handle: FunctionValue<'ctx>,
    pub(super) submit_closure: FunctionValue<'ctx>,
    pub(super) parallel_closure: FunctionValue<'ctx>,
    pub(super) panic_str: FunctionValue<'ctx>,
    pub(super) release_array: FunctionValue<'ctx>,
    pub(super) thread_spawn: FunctionValue<'ctx>,
    pub(super) thread_join: FunctionValue<'ctx>,
    pub(super) clock_mono: FunctionValue<'ctx>,
    pub(super) crypto_random: FunctionValue<'ctx>,
    pub(super) prng_seed: FunctionValue<'ctx>,
    pub(super) prng_next: FunctionValue<'ctx>,
    pub(super) file_open: FunctionValue<'ctx>,
    pub(super) file_close: FunctionValue<'ctx>,
    pub(super) file_read: FunctionValue<'ctx>,
    pub(super) file_read_err: FunctionValue<'ctx>,
    pub(super) file_write: FunctionValue<'ctx>,
    pub(super) file_flush: FunctionValue<'ctx>,
    pub(super) file_seek: FunctionValue<'ctx>,
    pub(super) file_tell: FunctionValue<'ctx>,
    pub(super) file_from_handle: FunctionValue<'ctx>,
    pub(super) io_is_tty: FunctionValue<'ctx>,
    pub(super) io_winsize: FunctionValue<'ctx>,
    pub(super) io_set_raw: FunctionValue<'ctx>,
    pub(super) path_exists: FunctionValue<'ctx>,
    pub(super) path_remove: FunctionValue<'ctx>,
    pub(super) fs_exists: FunctionValue<'ctx>,
    pub(super) fs_is_file: FunctionValue<'ctx>,
    pub(super) fs_is_dir: FunctionValue<'ctx>,
    pub(super) fs_stat: FunctionValue<'ctx>,
    pub(super) fs_stat_err: FunctionValue<'ctx>,
    pub(super) fs_read_dir: FunctionValue<'ctx>,
    pub(super) fs_read_dir_err: FunctionValue<'ctx>,
    pub(super) fs_glob: FunctionValue<'ctx>,
    pub(super) fs_glob_err: FunctionValue<'ctx>,
    pub(super) fs_read_link: FunctionValue<'ctx>,
    pub(super) fs_read_link_err: FunctionValue<'ctx>,
    pub(super) fs_remove: FunctionValue<'ctx>,
    pub(super) fs_remove_err: FunctionValue<'ctx>,
    pub(super) fs_remove_all: FunctionValue<'ctx>,
    pub(super) fs_remove_all_err: FunctionValue<'ctx>,
    pub(super) fs_mkdir_err: FunctionValue<'ctx>,
    pub(super) fs_copy_err: FunctionValue<'ctx>,
    pub(super) fs_move_err: FunctionValue<'ctx>,
    pub(super) fs_rename_err: FunctionValue<'ctx>,
    pub(super) fs_truncate_err: FunctionValue<'ctx>,
    pub(super) fs_chmod_err: FunctionValue<'ctx>,
    pub(super) fs_symlink_err: FunctionValue<'ctx>,
    pub(super) fs_fsync_err: FunctionValue<'ctx>,
    pub(super) fs_read_text: FunctionValue<'ctx>,
    pub(super) fs_read_text_err: FunctionValue<'ctx>,
    pub(super) fs_write_text: FunctionValue<'ctx>,
    pub(super) fs_write_text_err: FunctionValue<'ctx>,
    pub(super) fs_read_bytes: FunctionValue<'ctx>,
    pub(super) fs_read_bytes_err: FunctionValue<'ctx>,
    pub(super) fs_write_bytes: FunctionValue<'ctx>,
    pub(super) fs_write_bytes_err: FunctionValue<'ctx>,
    pub(super) fs_mmap: FunctionValue<'ctx>,
    pub(super) fs_mmap_err: FunctionValue<'ctx>,
    pub(super) fs_mmap_anon: FunctionValue<'ctx>,
    pub(super) fs_mmap_anon_err: FunctionValue<'ctx>,
    pub(super) fs_mmap_addr: FunctionValue<'ctx>,
    pub(super) fs_mmap_len: FunctionValue<'ctx>,
    pub(super) fs_mmap_flush: FunctionValue<'ctx>,
    pub(super) fs_mmap_close: FunctionValue<'ctx>,
    pub(super) test_assert: FunctionValue<'ctx>,
    pub(super) test_check: FunctionValue<'ctx>,
    pub(super) env_count: FunctionValue<'ctx>,
    pub(super) env_args_get: FunctionValue<'ctx>,
    pub(super) env_get: FunctionValue<'ctx>,
    pub(super) env_set: FunctionValue<'ctx>,
    pub(super) env_cwd: FunctionValue<'ctx>,
    pub(super) host_version: FunctionValue<'ctx>,
    pub(super) env_exit: FunctionValue<'ctx>,
    pub(super) net_connect: FunctionValue<'ctx>,
    pub(super) net_take_error: FunctionValue<'ctx>,
    pub(super) net_connect_wait: FunctionValue<'ctx>,
    pub(super) net_recv_wait: FunctionValue<'ctx>,
    pub(super) net_send_wait: FunctionValue<'ctx>,
    pub(super) net_recv_get: FunctionValue<'ctx>,
    pub(super) net_error_text: FunctionValue<'ctx>,
    pub(super) net_close: FunctionValue<'ctx>,
    pub(super) net_listener_bind: FunctionValue<'ctx>,
    pub(super) net_listener_port: FunctionValue<'ctx>,
    pub(super) net_listener_accept_start: FunctionValue<'ctx>,
    pub(super) net_listener_accept_wait: FunctionValue<'ctx>,
    pub(super) net_listener_close: FunctionValue<'ctx>,
    pub(super) tls_connect_start: FunctionValue<'ctx>,
    pub(super) tls_handshake_start: FunctionValue<'ctx>,
    pub(super) tls_handshake_wait: FunctionValue<'ctx>,
    pub(super) tls_recv_wait: FunctionValue<'ctx>,
    pub(super) tls_send_wait: FunctionValue<'ctx>,
    pub(super) tls_recv_get: FunctionValue<'ctx>,
    pub(super) tls_error_text: FunctionValue<'ctx>,
    pub(super) tls_close: FunctionValue<'ctx>,
    pub(super) proc_pid: FunctionValue<'ctx>,
    pub(super) proc_remove_env: FunctionValue<'ctx>,
    pub(super) proc_all_env_count: FunctionValue<'ctx>,
    pub(super) proc_all_env_get: FunctionValue<'ctx>,
    pub(super) proc_chdir: FunctionValue<'ctx>,
    pub(super) proc_spawn: FunctionValue<'ctx>,
    pub(super) proc_run: FunctionValue<'ctx>,
    pub(super) proc_pid_of: FunctionValue<'ctx>,
    pub(super) proc_write_stdin: FunctionValue<'ctx>,
    pub(super) proc_read_stdout: FunctionValue<'ctx>,
    pub(super) proc_read_stderr: FunctionValue<'ctx>,
    pub(super) proc_close_stdin: FunctionValue<'ctx>,
    pub(super) proc_wait: FunctionValue<'ctx>,
    pub(super) proc_try_wait: FunctionValue<'ctx>,
    pub(super) proc_kill: FunctionValue<'ctx>,
    pub(super) proc_take_stdout: FunctionValue<'ctx>,
    pub(super) proc_take_stderr: FunctionValue<'ctx>,
    pub(super) proc_exit_code: FunctionValue<'ctx>,
    pub(super) proc_forget: FunctionValue<'ctx>,
    pub(super) os_platform: FunctionValue<'ctx>,
    pub(super) os_arch: FunctionValue<'ctx>,
    pub(super) os_hostname: FunctionValue<'ctx>,
    pub(super) os_tmpdir: FunctionValue<'ctx>,
    pub(super) os_homedir: FunctionValue<'ctx>,
    pub(super) os_cpu_count: FunctionValue<'ctx>,
    pub(super) os_uptime: FunctionValue<'ctx>,
    pub(super) map_new: FunctionValue<'ctx>,
    pub(super) map_set: FunctionValue<'ctx>,
    pub(super) map_get: FunctionValue<'ctx>,
    pub(super) map_has: FunctionValue<'ctx>,
    pub(super) map_delete: FunctionValue<'ctx>,
    pub(super) map_len: FunctionValue<'ctx>,
    pub(super) map_clear: FunctionValue<'ctx>,
    pub(super) map_keys: FunctionValue<'ctx>,
    pub(super) map_values: FunctionValue<'ctx>,
    pub(super) gmap_new: FunctionValue<'ctx>,
    pub(super) gmap_free: FunctionValue<'ctx>,
    pub(super) gmap_set: FunctionValue<'ctx>,
    pub(super) gmap_get: FunctionValue<'ctx>,
    pub(super) gmap_has: FunctionValue<'ctx>,
    pub(super) gmap_delete: FunctionValue<'ctx>,
    pub(super) gmap_len: FunctionValue<'ctx>,
    pub(super) gmap_clear: FunctionValue<'ctx>,
    pub(super) gmap_keys: FunctionValue<'ctx>,
    pub(super) gmap_values: FunctionValue<'ctx>,
    pub(super) json_parse: FunctionValue<'ctx>,
    pub(super) json_parse_typed: FunctionValue<'ctx>,
    pub(super) json_stringify_into: FunctionValue<'ctx>,
    pub(super) json_stringify: FunctionValue<'ctx>,
    pub(super) json_unwrap: FunctionValue<'ctx>,
    pub(super) dns_lookup_start: FunctionValue<'ctx>,
    pub(super) dns_lookup_wait: FunctionValue<'ctx>,
    pub(super) dns_lookup_get: FunctionValue<'ctx>,
    pub(super) dns_lookup_error: FunctionValue<'ctx>,
    pub(super) sync_atomic_get: FunctionValue<'ctx>,
    pub(super) black_box: FunctionValue<'ctx>,
    pub(super) sync_atomic_set: FunctionValue<'ctx>,
    pub(super) sync_atomic_fetch_add: FunctionValue<'ctx>,
    pub(super) sync_atomic_cas: FunctionValue<'ctx>,
    pub(super) sync_channel_send: FunctionValue<'ctx>,
    pub(super) sync_channel_send_str: FunctionValue<'ctx>,
    pub(super) sync_channel_send_obj: FunctionValue<'ctx>,
    pub(super) sync_channel_send_array: FunctionValue<'ctx>,
    pub(super) sync_channel_recv: FunctionValue<'ctx>,
    pub(super) sync_channel_try_recv: FunctionValue<'ctx>,
    pub(super) sync_channel_len: FunctionValue<'ctx>,
    pub(super) fs_pool_depth: FunctionValue<'ctx>,
    pub(super) sync_channel_drop: FunctionValue<'ctx>,
    pub(super) debug_live: FunctionValue<'ctx>,
    pub(super) defer_push: FunctionValue<'ctx>,
    pub(super) defer_pop: FunctionValue<'ctx>,
    pub(super) defer_len: FunctionValue<'ctx>,
    pub(super) any_tag: FunctionValue<'ctx>,
    pub(super) obj_class: FunctionValue<'ctx>,
    pub(super) error_set: FunctionValue<'ctx>,
    pub(super) error_take: FunctionValue<'ctx>,
    pub(super) error_class: FunctionValue<'ctx>,
    pub(super) error_unbox: FunctionValue<'ctx>,
    pub(super) error_str: FunctionValue<'ctx>,
    pub(super) error_release: FunctionValue<'ctx>,
    pub(super) note_type: FunctionValue<'ctx>,
    pub(super) type_name: FunctionValue<'ctx>,
    pub(super) typeof_any: FunctionValue<'ctx>,
    pub(super) io_pretty: FunctionValue<'ctx>,
    pub(super) note_array_kind: FunctionValue<'ctx>,
    pub(super) note_fields: FunctionValue<'ctx>,
    pub(super) note_enum: FunctionValue<'ctx>,
    pub(super) note_namespace: FunctionValue<'ctx>,
    pub(super) array_slice: FunctionValue<'ctx>,
    pub(super) mutex_lock: FunctionValue<'ctx>,
    pub(super) mutex_unlock: FunctionValue<'ctx>,
    pub(super) mutex_try_lock: FunctionValue<'ctx>,
    pub(super) rwlock_read_lock: FunctionValue<'ctx>,
    pub(super) rwlock_read_unlock: FunctionValue<'ctx>,
    pub(super) rwlock_write_lock: FunctionValue<'ctx>,
    pub(super) rwlock_write_unlock: FunctionValue<'ctx>,
    pub(super) rwlock_try_read_lock: FunctionValue<'ctx>,
    pub(super) rwlock_try_write_lock: FunctionValue<'ctx>,
    pub(super) condvar_wait: FunctionValue<'ctx>,
    pub(super) condvar_wait_timeout: FunctionValue<'ctx>,
    pub(super) condvar_notify_one: FunctionValue<'ctx>,
    pub(super) condvar_notify_all: FunctionValue<'ctx>,
    pub(super) barrier_wait: FunctionValue<'ctx>,
    pub(super) vec_minnum: FunctionValue<'ctx>,
    pub(super) vec_maxnum: FunctionValue<'ctx>,
    pub(super) vec_sqrt: FunctionValue<'ctx>,
    pub(super) pool_shutdown: FunctionValue<'ctx>,
    pub(super) pool_join: FunctionValue<'ctx>,
    pub(super) pool_parallel_for: FunctionValue<'ctx>,
    pub(super) pool_init: FunctionValue<'ctx>,
    pub(super) math_sqrt: FunctionValue<'ctx>,
    pub(super) math_sin: FunctionValue<'ctx>,
    pub(super) math_cos: FunctionValue<'ctx>,
    pub(super) math_tan: FunctionValue<'ctx>,
    pub(super) math_atan2: FunctionValue<'ctx>,
    pub(super) math_pow: FunctionValue<'ctx>,
    pub(super) math_floor: FunctionValue<'ctx>,
    pub(super) math_ceil: FunctionValue<'ctx>,
    pub(super) math_round: FunctionValue<'ctx>,
    pub(super) math_log: FunctionValue<'ctx>,
    pub(super) strings: BTreeMap<String, inkwell::values::GlobalValue<'ctx>>,
    pub(super) bytes_fns: BTreeMap<String, FunctionValue<'ctx>>,
    pub(super) locals: Vec<inkwell::values::PointerValue<'ctx>>,
    pub(super) blocks: Vec<inkwell::basic_block::BasicBlock<'ctx>>,
    pub(super) stack_slots: Vec<inkwell::values::PointerValue<'ctx>>,
    pub(super) stack_next: usize,
    pub(super) stack: BTreeSet<Local>,
    pub(super) ftypes: Vec<LirType>,
    pub(super) ret_slots: usize,
    pub(super) owned: BTreeSet<Local>,
    pub(super) ever_owned: BTreeSet<Local>,
    pub(super) nborrowed: usize,
    pub(super) dom: lir::licm::DominatorTree,
    pub(super) cur_block: usize,
    pub(super) last_write: std::cell::RefCell<BTreeMap<Local, usize>>,
    pub(super) in_enum_dtor: bool,
    pub(super) defers: Vec<Vec<Instr>>,
    pub(super) defer_base: Option<inkwell::values::PointerValue<'ctx>>,
}

pub(super) fn lower_instr(cx: &mut FnCx, lir: &Module, ins: &Instr, fname: &str) -> Result<(), Diagnostic> {
    let _ = fname;
    match ins {
        Instr::Const { .. } => casts::lower_casts(cx, lir, ins, fname)?,
        Instr::Cast { .. } => casts::lower_casts(cx, lir, ins, fname)?,
        Instr::Copy { .. } => casts::lower_casts(cx, lir, ins, fname)?,
        Instr::ObjNew { .. } => mem::lower_mem(cx, lir, ins, fname)?,
        Instr::StackAlloc { .. } => mem::lower_mem(cx, lir, ins, fname)?,
        Instr::EnumNew { .. } => mem::lower_mem(cx, lir, ins, fname)?,
        Instr::EnumPayload { .. } => mem::lower_mem(cx, lir, ins, fname)?,
        Instr::EnumTag { .. } => mem::lower_mem(cx, lir, ins, fname)?,
        Instr::GetField { .. } => mem::lower_mem(cx, lir, ins, fname)?,
        Instr::SetField { .. } => mem::lower_mem(cx, lir, ins, fname)?,
        Instr::GetFieldByName { .. } => mem::lower_mem(cx, lir, ins, fname)?,
        Instr::SetFieldByName { .. } => mem::lower_mem(cx, lir, ins, fname)?,
        Instr::GenRefOf { .. } => mem::lower_mem(cx, lir, ins, fname)?,
        Instr::GenRefEmpty { .. } => mem::lower_mem(cx, lir, ins, fname)?,
        Instr::GenRefGet { .. } => mem::lower_mem(cx, lir, ins, fname)?,
        Instr::GenRefInvalidate { .. } => mem::lower_mem(cx, lir, ins, fname)?,
        Instr::ThreadSpawn { .. } => calls::lower_calls(cx, lir, ins, fname)?,
        Instr::ThreadJoin { .. } => calls::lower_calls(cx, lir, ins, fname)?,
        Instr::PoolInit { .. } => calls::lower_calls(cx, lir, ins, fname)?,
        Instr::PoolSubmit { .. } => calls::lower_calls(cx, lir, ins, fname)?,
        Instr::PoolParallelFor { .. } => calls::lower_calls(cx, lir, ins, fname)?,
        Instr::PoolJoin { .. } => calls::lower_calls(cx, lir, ins, fname)?,
        Instr::PoolShutdown { .. } => calls::lower_calls(cx, lir, ins, fname)?,
        Instr::VecNew { .. } => arith::lower_arith(cx, lir, ins, fname)?,
        Instr::VecSplat { .. } => arith::lower_arith(cx, lir, ins, fname)?,
        Instr::VecExtract { .. } => arith::lower_arith(cx, lir, ins, fname)?,
        Instr::VecInsert { .. } => arith::lower_arith(cx, lir, ins, fname)?,
        Instr::VecArith { .. } => arith::lower_arith(cx, lir, ins, fname)?,
        Instr::VecUnary { .. } => arith::lower_arith(cx, lir, ins, fname)?,
        Instr::VecDot { .. } => arith::lower_arith(cx, lir, ins, fname)?,
        Instr::Retain { .. } => mem::lower_mem(cx, lir, ins, fname)?,
        Instr::ClosureNew { .. } => mem::lower_mem(cx, lir, ins, fname)?,
        Instr::ArrayNew { .. } => mem::lower_mem(cx, lir, ins, fname)?,
        Instr::ArrayPush { .. } => mem::lower_mem(cx, lir, ins, fname)?,
        Instr::ArrayGet { .. } => mem::lower_mem(cx, lir, ins, fname)?,
        Instr::ArraySet { .. } => mem::lower_mem(cx, lir, ins, fname)?,
        Instr::ArrayLen { .. } => mem::lower_mem(cx, lir, ins, fname)?,
        Instr::Release { .. } => mem::lower_mem(cx, lir, ins, fname)?,
        Instr::PtrLoad { .. } => mem::lower_mem(cx, lir, ins, fname)?,
        Instr::PtrStore { .. } => mem::lower_mem(cx, lir, ins, fname)?,
        Instr::ReleaseAs { .. } => mem::lower_mem(cx, lir, ins, fname)?,
        Instr::ReleaseField { .. } => mem::lower_mem(cx, lir, ins, fname)?,
        Instr::Arith { .. } => arith::lower_arith(cx, lir, ins, fname)?,
        Instr::Fma { .. } => arith::lower_arith(cx, lir, ins, fname)?,
        Instr::Cmp { .. } => arith::lower_arith(cx, lir, ins, fname)?,
        Instr::Not { .. } => arith::lower_arith(cx, lir, ins, fname)?,
        Instr::Neg { .. } => arith::lower_arith(cx, lir, ins, fname)?,
        Instr::Convert { .. } => casts::lower_casts(cx, lir, ins, fname)?,
        Instr::Concat { .. } => casts::lower_casts(cx, lir, ins, fname)?,
        Instr::ToStr { .. } => casts::lower_casts(cx, lir, ins, fname)?,
        Instr::Call { .. } => calls::lower_calls(cx, lir, ins, fname)?,
        Instr::Defer { .. } => control::lower_control(cx, lir, ins, fname)?,
        Instr::RunDefers { .. } => control::lower_control(cx, lir, ins, fname)?,
        _ => return Err(Diagnostic::new(Code::E108, "llvm subset: unsupported instr")),
    }
    Ok(())
}
