[package]
name = "llvm"
version = "0.1.0"
edition.workspace = true

[dependencies]
diagnostics = { path = "../diagnostics" }
lir = { path = "../lir" }
runtime = { path = "../runtime" }
inkwell = { version = "=0.10.0", features = ["llvm22-1"] }
llvm-sys = "=221.1.0"

[dev-dependencies]
frontend = { path = "../frontend" }
