use diagnostics::Span;

#[derive(Clone, Debug, PartialEq)]
pub enum TokenKind {
    Ident(String),
    Int(i64),
    Float(f64),
    StrOpen,
    StrText(String),
    DocComment(String),
    DocModule(String),
    InterpOpen,
    InterpClose,
    StrClose,
    True,
    False,
    Null,
    This,
    Super,
    Class,
    Struct,
    Record,
    Trait,
    Interface,
    Extension,
    Enum,
    Fn,
    Init,
    New,
    Deinit,
    OnReload,
    Extends,
    With,
    Let,
    Const,
    Static,
    If,
    Else,
    For,
    While,
    In,
    Return,
    Break,
    Continue,
    Try,
    Catch,
    Finally,
    Throw,
    Throws,
    Defer,
    Guard,
    Switch,
    Case,
    Default,
    Do,
    Fallthrough,
    Is,
    Import,
    Export,
    From,
    As,
    Public,
    Private,
    Unsafe,
    Comptime,
    Native,
    Async,
    Await,
    Pass,
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Comma,
    Semi,
    Colon,
    Dot,
    DotDot,
    DotDotEq,
    Ellipsis,
    Arrow,
    FatArrow,
    Plus,
    Minus,
    PlusPlus,
    MinusMinus,
    Star,
    Slash,
    Percent,
    Eq,
    PlusEq,
    MinusEq,
    StarEq,
    SlashEq,
    PercentEq,
    EqEq,
    BangEq,
    Lt,
    LtEq,
    Gt,
    GtEq,
    Shl,
    Shr,
    Zshr,
    ShlEq,
    ShrEq,
    ZshrEq,
    Bang,
    Amp,
    AmpAmp,
    Pipe,
    PipePipe,
    Caret,
    Tilde,
    Question,
    QuestionQuestion,
    QuestionDot,
    Hash,
    Eof,
}

#[derive(Clone, Debug, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}

pub fn keyword(word: &str) -> Option<TokenKind> {
    Some(match word {
        "true" => TokenKind::True,
        "false" => TokenKind::False,
        "null" => TokenKind::Null,
        "this" => TokenKind::This,
        "super" => TokenKind::Super,
        "class" => TokenKind::Class,
        "struct" => TokenKind::Struct,
        "record" => TokenKind::Record,
        "trait" => TokenKind::Trait,
        "interface" => TokenKind::Interface,
        "extension" => TokenKind::Extension,
        "enum" => TokenKind::Enum,
        "fn" => TokenKind::Fn,
        "init" => TokenKind::Init,
        "new" => TokenKind::New,
        "deinit" => TokenKind::Deinit,
        "onReload" => TokenKind::OnReload,
        "extends" => TokenKind::Extends,
        "with" => TokenKind::With,
        "let" => TokenKind::Let,
        "const" => TokenKind::Const,
        "static" => TokenKind::Static,
        "if" => TokenKind::If,
        "else" => TokenKind::Else,
        "for" => TokenKind::For,
        "while" => TokenKind::While,
        "in" => TokenKind::In,
        "return" => TokenKind::Return,
        "break" => TokenKind::Break,
        "continue" => TokenKind::Continue,
        "try" => TokenKind::Try,
        "catch" => TokenKind::Catch,
        "finally" => TokenKind::Finally,
        "throw" => TokenKind::Throw,
        "throws" => TokenKind::Throws,
        "defer" => TokenKind::Defer,
        "guard" => TokenKind::Guard,
        "switch" => TokenKind::Switch,
        "case" => TokenKind::Case,
        "default" => TokenKind::Default,
        "do" => TokenKind::Do,
        "fallthrough" => TokenKind::Fallthrough,
        "is" => TokenKind::Is,
        "import" => TokenKind::Import,
        "export" => TokenKind::Export,
        "from" => TokenKind::From,
        "as" => TokenKind::As,
        "public" | "pub" => TokenKind::Public,
        "private" => TokenKind::Private,
        "unsafe" => TokenKind::Unsafe,
        "comptime" => TokenKind::Comptime,
        "native" => TokenKind::Native,
        "async" => TokenKind::Async,
        "await" => TokenKind::Await,
        "pass" => TokenKind::Pass,
        _ => return None,
    })
}
